nginx:
  hostname: nginx
  build: docker/nginx_stash
  ports:
    - "80:80"
    - "443:443"
  links:
    - stash

stash:
  hostname: stash
  build: docker/stash
  ports:
    - "7990:7990" # no cache
    - "7999:7999" # ssh port
  links:
    - database
  volumes:
    - stash-home:/opt/stash-home

database:
  hostname: database
  build: docker/postgres
  volumes:
    - tmp:/tmp # import backups
  volumes_from:
    - persistent

persistent:
  image: busybox
  volumes:
    - /var/lib/postgresql/data
