nginx:
  hostname: nginx
  build: docker/nginx_crowd
  ports:
    - "80:80"
    - "443:443"
  links:
    - crowd

crowd:
  hostname: crowd
  build: docker/crowd
  ports:
    - "8095:8095" # no cache
  links:
    - database
  volumes:
    - crowd-home:/opt/crowd-home

database:
  hostname: database
  build: docker/postgres
  volumes:
    - tmp:/tmp # import backups
  volumes_from:
    - persistent

persistent:
  image: busybox
  volumes:
    - /var/lib/postgresql/data
