stash:
  build: docker/stash
  ports:
    - "7990:7990" # no cache
    - "7999:7999" # ssh port
  links:
    - database
  volumes:
    - home:/opt/stash-home
  restart: always

nginx:
  hostname: nginx
  build: docker/nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - stash
  restart: always

database:
  hostname: database
  build: docker/postgres
  volumes:
    - tmp:/tmp # import backups
    - data:/var/lib/postgresql/data
  restart: always
